[package]
name = "checked-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
convert_case = "0.6"

[lib]
proc-macro = true
